#!/usr/bin/env python3
"""
Generate IGCSE Chemistry Obsidian wiki files from exam database.
Research-backed content synthesized from 1,229 Q+A pairs across 38 papers.
Output: wiki-web/wiki/IGCSE Chemistry/*.md
"""

import json, re, os
from pathlib import Path
from collections import defaultdict, Counter
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
WIKI_DIR = ROOT / "wiki-web" / "wiki" / "IGCSE Chemistry"
CONTENT_DB = ROOT / "web" / "data" / "chem-content-db.js"
EXAM_DATA = ROOT / "web" / "data" / "chem-exam-data.js"
NOW = "2026-07-14"

# ── Parse JS data files ──────────────────────────────────────────

def load_data():
    """Load all Q+A entries from pre-extracted JSON files."""
    print("Loading data...")

    # Load pre-extracted JSON (generated by: node -e "vm.Script(content + '; VAR').runInNewContext()")
    content_json = ROOT.parent / "tmp" / "chem-content-db.json"
    exam_json = ROOT.parent / "tmp" / "chem-exam-data.json"

    # Also try /tmp/
    if not content_json.exists():
        content_json = Path("/tmp/chem-content-db.json")
    if not exam_json.exists():
        exam_json = Path("/tmp/chem-exam-data.json")

    with open(content_json) as f:
        db = json.load(f)
    with open(exam_json) as f:
        exams = json.load(f)

    entries = []
    for topic, qlist in db.items():
        if topic.startswith('_'):
            continue
        if isinstance(qlist, list):
            for item in qlist:
                if isinstance(item, dict):
                    item['_topic'] = topic
                    entries.append(item)

    print(f"  Loaded {len(entries)} Q+A entries from {len(exams)} papers")
    return entries, exams


# ── IGCSE Syllabus Topic Definitions ─────────────────────────────

TOPICS = {
    # Topic 1: Particulate Nature of Matter
    "States of Matter": {
        "section": "1. The Particulate Nature of Matter",
        "tags": ["particulate-nature"],
        "summary": "The kinetic particle theory explains the properties and behaviour of solids, liquids, and gases in terms of particle arrangement, movement, and energy.",
        "keywords": [
            r"\b(?:solid|liquid|gas)\b.*\b(?:state|melt|boil|freez|condens|sublim)",
            r"\bkinetic\s*(?:particle|theory)\b",
            r"\b(?:melting|boiling)\s*point\b",
            r"\bBrownian\b", r"\bheating\s*curve\b",
            r"\bparticle\s*(?:movement|arrangement|energy)\b",
            r"\b(?:expansion|contraction)\b",
            r"\bchange\s*of\s*state\b", r"\bstate\s*change\b",
            r"\b(?:sublimation|deposition)\b"
        ],
    },
    "Diffusion": {
        "section": "1. The Particulate Nature of Matter",
        "tags": ["particulate-nature"],
        "summary": "Diffusion is the net movement of particles from a region of higher concentration to lower concentration, explained by random particle motion.",
        "keywords": [
            r"\bdiffus", r"\bmov(?:e|ing|ement).*random\b",
            r"\bconcentration\s*gradient\b",
            r"\bammonia.*hydrogen\s*chloride\b", r"\bHCl.*NH3\b",
            r"\bBrownian\s*motion\b", r"\brandom\s*motion\b",
            r"\b(?:perfume|bromine)\b.*\bdiffus"
        ],
    },

    # Topic 2: Experimental Techniques
    "Experimental Techniques": {
        "section": "2. Experimental Techniques",
        "tags": ["practical-skills"],
        "summary": "Methods for separating and purifying substances including chromatography, distillation, filtration, crystallisation, and determining purity.",
        "keywords": [
            r"\bchromatograph", r"\bRf\s*value", r"\blocating\s*agent",
            r"\b(?:simple|fractional)\s*distil", r"\bdistillate\b",
            r"\bfiltrat", r"\bresidue\b", r"\bcrystalli[sz]",
            r"\bpure\s*substance\b", r"\bimpur", r"\bmelting\s*point\b.*\b(?:pure|sharp|range)\b",
            r"\bseparat(?:ing|e|ion)\b.*\b(?:mixture|method)\b",
            r"\b(?:solvent|solute|solution)\b.*\b(?:evaporat|boil)\b",
            r"\bpaper\s*chromatography\b", r"\bretention\s*factor\b"
        ],
    },
    "Chemical Tests": {
        "section": "2. Experimental Techniques",
        "tags": ["practical-skills"],
        "summary": "Qualitative chemical tests for identifying gases, cations, anions, and water using specific reagents and observing characteristic results.",
        "keywords": [
            r"\btest\s*for\b", r"\bflame\s*test\b",
            r"\b(?:aqueous\s*)?sodium\s*hydroxide\b.*\bprecipitate\b",
            r"\b(?:aqueous\s*)?ammonia\b.*\bprecipitate\b",
            r"\bsilver\s*nitrate\b", r"\bbarium\s*(?:chloride|nitrate)\b",
            r"\blime\s*water\b", r"\bglowing\s*splint\b", r"\blit\s*splint\b",
            r"\bsqueaky\s*pop\b", r"\bdamp\s*(?:red|blue)\s*litmus\b",
            r"\b(?:white|blue|green|brown|cream)\s*precipitate\b",
            r"\bacidified\s*(?:potassium|silver|barium)\b",
            r"\b(?:cation|anion)\s*test", r"\bchemical\s*test\b",
            r"\b(?:bleach|turns|goes)\s*(?:milky|cloudy)\b"
        ],
    },

    # Topic 3: Atoms, Elements and Compounds
    "Atomic Structure": {
        "section": "3. Atoms, Elements and Compounds",
        "tags": ["atomic-structure"],
        "summary": "Atoms consist of protons, neutrons, and electrons. Atomic number (Z) equals protons; mass number equals protons + neutrons. Electrons are arranged in shells (2.8.8...).",
        "keywords": [
            r"\bproton\b", r"\bneutron\b", r"\belectron\b",
            r"\batomic\s*(?:number|mass)\b", r"\bmass\s*number\b",
            r"\belectronic\s*(?:config|struct|arrangement)", r"\b2[\.,]8[\.,]",
            r"\bisotope", r"\bnucleus\b", r"\bnucleon\s*number",
            r"\brelative\s*atomic\s*mass\b", r"\bsubatomic\b",
            r"\b(?:proton|atomic)\s*number\b.*\b(?:electron|element)\b"
        ],
    },
    "Ions and Ionic Bonds": {
        "section": "3. Atoms, Elements and Compounds",
        "tags": ["bonding"],
        "summary": "Ionic bonding involves electron transfer from a metal to a non-metal, forming oppositely charged ions held in a giant ionic lattice by strong electrostatic forces.",
        "keywords": [
            r"\bionic\s*bond", r"\bgiant\s*ionic",
            r"\b(?:positive|negative)\s*ion", r"\bcation\b", r"\banion\b",
            r"\btransfer.*electron", r"\belectrostatic\b",
            r"\b(?:lose|lost|losing)\s*electron", r"\b(?:gain|gained)\s*electron",
            r"\b(?:high|low)\s*(?:melting|boiling).*point",
            r"\bconduct.*(?:electricity|molten|dissolved|aqueous)\b",
            r"\bdot[\s-]*(?:and|&)[\s-]*cross\b", r"\blattice\b"
        ],
    },
    "Covalent Bonding": {
        "section": "3. Atoms, Elements and Compounds",
        "tags": ["bonding"],
        "summary": "Covalent bonding involves sharing of electron pairs between non-metal atoms. Can form simple molecular structures or giant covalent networks (diamond, graphite, SiO₂).",
        "keywords": [
            r"\bcovalent\s*bond", r"\bshare.*electron",
            r"\bsimple\s*molecular", r"\bintermolecular\b",
            r"\bdiamond\b", r"\bgraphite\b", r"\bsilicon\s*dioxide\b", r"\bsilica\b",
            r"\bmacromolecule", r"\bgiant\s*covalent\b",
            r"\b(?:low|high)\s*(?:melting|boiling).*point",
            r"\bdelocali[sz]ed\s*electron",
            r"\bdot[\s-]*(?:and|&)[\s-]*cross\b",
            r"\b(?:single|double|triple)\s*bond\b"
        ],
    },
    "Metallic Bonding": {
        "section": "3. Atoms, Elements and Compounds",
        "tags": ["bonding"],
        "summary": "Metallic bonding is the electrostatic attraction between a lattice of positive metal ions and a sea of delocalised electrons, giving metals their characteristic properties.",
        "keywords": [
            r"\bmetallic\s*bond", r"\bdelocali[sz]ed\s*electron",
            r"\bsea\s*of\s*electrons", r"\bmalleable\b", r"\bductile\b",
            r"\b(?:thermal|electrical)\s*conductor\b",
            r"\balloy\b", r"\b(?:pure|solid)\s*metal\b",
            r"\bmetal\s*lattice\b", r"\bpositive\s*(?:metal\s*)?ions\b"
        ],
    },
    "Giant Structures": {
        "section": "3. Atoms, Elements and Compounds",
        "tags": ["bonding"],
        "summary": "Comparison of giant ionic, giant covalent, and giant metallic structures — their bonding, properties, and uses explained by structure.",
        "keywords": [
            r"\bgiant\s*(?:ionic|covalent|metallic|structure)",
            r"\b(?:ionic|covalent)\s*lattice",
            r"\bcompare.*\b(?:structure|bonding|property)\b",
            r"\bexplain.*\b(?:conduct|melt|boil|hard|strong)\b",
            r"\bwhy.*\b(?:conduct|melt|boil|hard|strong)\b"
        ],
    },

    # Topic 4: Stoichiometry
    "Relative Masses and Moles": {
        "section": "4. Stoichiometry",
        "tags": ["stoichiometry"],
        "summary": "The mole is the unit of amount of substance. One mole contains 6.02×10²³ particles. Molar mass (Mr) is the mass of one mole in grams.",
        "keywords": [
            r"\bmole\b", r"\bmolar\s*mass\b",
            r"\brelative\s*(?:atomic|formula|molecular)\s*mass\b",
            r"\bAr\b.*\bMr\b", r"\bAvogadro",
            r"\b6[\.,]02\s*[×x]\s*10", r"\bgram\s*per\s*mole\b"
        ],
    },
    "Empirical and Molecular Formulae": {
        "section": "4. Stoichiometry",
        "tags": ["stoichiometry"],
        "summary": "Empirical formula is the simplest whole-number ratio of atoms in a compound. Molecular formula is the actual number of atoms of each element in a molecule.",
        "keywords": [
            r"\bempirical\s*formula", r"\bmolecular\s*formula",
            r"\bpercentage\s*composition", r"\bpercent.*by.*mass\b",
            r"\bsimplest\s*ratio\b", r"\breacting\s*mass"
        ],
    },
    "Reacting Masses": {
        "section": "4. Stoichiometry",
        "tags": ["stoichiometry"],
        "summary": "Calculate masses of reactants and products using balanced equations and mole ratios. Includes percentage yield and limiting reactant calculations.",
        "keywords": [
            r"\breacting\s*mass", r"\blimiting\s*reactant",
            r"\bpercentage\s*yield", r"\bpercent\s*yield",
            r"\btheoretical\s*yield\b", r"\bactual\s*yield\b",
            r"\bcalculate\s*(?:the\s*)?\b(?:mass|mole|volume)\b",
            r"\bexcess\b", r"\bmole\s*ratio"
        ],
    },
    "Concentration and Gas Volumes": {
        "section": "4. Stoichiometry",
        "tags": ["stoichiometry"],
        "summary": "Concentration measured in mol/dm³ or g/dm³. One mole of any gas occupies 24 dm³ at room temperature and pressure (r.t.p.). Titration calculations.",
        "keywords": [
            r"\bconcentrat", r"\bmol\s*(?:/|per)\s*dm", r"\bg\s*(?:/|per)\s*dm",
            r"\b(?:24|24000)\s*dm", r"\bmolar\s*(?:gas\s*)?volume\b",
            r"\btitrat", r"\b(?:burette|pipette)\b",
            r"\br[\.,]t[\.,]p\b", r"\broom\s*temperature.*pressure\b",
            r"\bdm3\b", r"\bcm3\b"
        ],
    },

    # Topic 5: Electrolysis
    "Electrolysis": {
        "section": "5. Electricity and Chemistry",
        "tags": ["electrolysis"],
        "summary": "Electrolysis is the decomposition of an ionic compound by passing electricity through it when molten or in aqueous solution.",
        "keywords": [
            r"\belectrolysis\b", r"\belectrolyte\b",
            r"\banode\b", r"\bcathode\b", r"\belectrode\b",
            r"\bmolten\b", r"\breduction.*cathode\b",
            r"\boxidation.*anode\b", r"\bdischarg",
            r"\b(?:positive|negative)\s*electrode",
            r"\bionic\s*compound.*\b(?:molten|dissolved)\b"
        ],
    },
    "Electrolysis of Aqueous Solutions": {
        "section": "5. Electricity and Chemistry",
        "tags": ["electrolysis"],
        "summary": "In aqueous electrolysis, the ions discharged depend on the reactivity series and concentration. Water can be oxidized/reduced in competition with dissolved ions.",
        "keywords": [
            r"\baqueous\s*(?:solution\s*)?electrolysis",
            r"\b(?:brine|salt\s*water|sodium\s*chloride)\b.*\belectrolysis",
            r"\bdischarge\s*series\b",
            r"\b(?:hydrogen|oxygen|chlorine)\b.*\b(?:produced|formed|given|evolved)\b",
            r"\b(?:halide|sulfate|nitrate)\b.*\belectro",
            r"\bhydrox(?:ide|yl)\s*ion", r"\bOH[\s-]"
        ],
    },
    "Electrolysis Applications": {
        "section": "5. Electricity and Chemistry",
        "tags": ["electrolysis"],
        "summary": "Industrial applications: extraction of aluminium from bauxite (Hall-Héroult process), copper refining, electroplating with chromium/silver, and brine electrolysis.",
        "keywords": [
            r"\baluminium.*extract", r"\bbauxite\b", r"\bcryolite\b",
            r"\belectroplat", r"\bcopper\s*refin",
            r"\b(?:Hall|Héroult)\b", r"\bbrine\b.*\belectrolysis",
            r"\b(?:anode|sludge|slime)\b", r"\b(?:pure|impure)\s*copper\b"
        ],
    },

    # Topic 6: Chemical Energetics
    "Energetics of Reactions": {
        "section": "6. Chemical Energetics",
        "tags": ["energetics"],
        "summary": "Exothermic reactions release heat to surroundings (ΔH negative). Endothermic reactions absorb heat (ΔH positive). Energy level diagrams show relative energies.",
        "keywords": [
            r"\bexothermic\b", r"\bendothermic\b",
            r"\benthalpy\b", r"\bΔH\b", r"\bdelta\s*H\b",
            r"\benergy\s*(?:level|profile)\s*diagram",
            r"\bactivation\s*energy\b",
            r"\b(?:releases|absorbs?|gives?\s*out|takes?\s*in)\s*(?:heat|energy|thermal)",
            r"\btemperature\s*(?:increase|decrease|rise|fall|change)\b",
            r"\bbond\s*(?:making|breaking|form)\b"
        ],
    },
    "Bond Energy Calculations": {
        "section": "6. Chemical Energetics",
        "tags": ["energetics"],
        "summary": "ΔH = sum of bond energies broken − sum of bond energies formed. Bond breaking is endothermic; bond making is exothermic.",
        "keywords": [
            r"\bbond\s*energy\b.*\bcalculat",
            r"\b(?:broken|break|breaking)\b.*\b(?:made|form|making)\b",
            r"\bbond\s*energy\b.*\b(?:kJ|kilojoule)",
            r"\benergy\s*change\b.*\bcalculat",
            r"\bsum\s*of\s*bond\s*energ"
        ],
    },

    # Topic 7: Chemical Reactions
    "Rates of Reaction": {
        "section": "7. Chemical Reactions",
        "tags": ["reactions"],
        "summary": "Reaction rate depends on concentration, temperature, surface area, and catalysts. Explained by collision theory — particles must collide with sufficient energy (activation energy) and correct orientation.",
        "keywords": [
            r"\brate\s*of\s*reaction", r"\bcollision\s*theory",
            r"\bsurface\s*area\b", r"\bconcentration\b.*\b(?:affect|rate|increase)\b",
            r"\btemperature\b.*\b(?:affect|rate|increase)\b",
            r"\bcatalyst\b.*\b(?:speed|rate|lower)\b",
            r"\bsuccessful\s*collision", r"\bfrequency\s*of\s*collision",
            r"\bactivation\s*energy\b", r"\bmeasuring\s*rate",
            r"\b(?:faster|slower)\s*reaction"
        ],
    },
    "Reversible Reactions": {
        "section": "7. Chemical Reactions",
        "tags": ["reactions"],
        "summary": "Reversible reactions reach dynamic equilibrium when forward and backward rates are equal. Le Chatelier's principle predicts the effect of changing conditions.",
        "keywords": [
            r"\breversible\b", r"\bequilibrium\b",
            r"\bLe\s*Chatelier", r"\bdynamic\s*equilibrium\b",
            r"\bforward\s*(?:and|&)\s*backward\b",
            r"\b(?:increase|decrease)\s*(?:temperature|pressure|concentration)\b.*\bequilibrium",
            r"\bposition\s*of\s*equilibrium\b",
            r"\bHaber\s*process\b", r"\bContact\s*process\b"
        ],
    },
    "Redox Reactions": {
        "section": "7. Chemical Reactions",
        "tags": ["reactions"],
        "summary": "Oxidation is loss of electrons, gain of oxygen, or increase in oxidation number. Reduction is gain of electrons, loss of oxygen, or decrease in oxidation number.",
        "keywords": [
            r"\boxid(?:ation|e|ising)\b", r"\breduc(?:tion|e|ing)\b",
            r"\bredox\b", r"\bloss\s*of\s*electron",
            r"\bgain\s*of\s*electron", r"\boxidation\s*(?:number|state)\b",
            r"\boxidising\s*agent", r"\breducing\s*agent",
            r"\brust", r"\bcorrosion\b", r"\bsacrificial\s*protect"
        ],
    },

    # Topic 8: Acids, Bases and Salts
    "Acids and Bases": {
        "section": "8. Acids, Bases and Salts",
        "tags": ["acids-bases"],
        "summary": "Acids are proton (H⁺) donors; bases are proton acceptors. Strong acids fully dissociate in water; weak acids partially dissociate. Common acids: HCl, H₂SO₄, HNO₃.",
        "keywords": [
            r"\bacids?\b", r"\bbase", r"\balkali",
            r"\b(?:strong|weak)\s*acid\b",
            r"\b(?:fully|partially|completely)\s*(?:dissociat|ionis|ioniz)",
            r"\b(?:proton|H\+|H3O\+|H\s*\+\s*)\s*(?:donor|acceptor)",
            r"\bhydrochloric\b", r"\bsulfuric\b", r"\bnitric\b",
            r"\bethanoic\b", r"\bcarboxylic\s*acid\b"
        ],
    },
    "Indicators and pH": {
        "section": "8. Acids, Bases and Salts",
        "tags": ["acids-bases"],
        "summary": "pH scale (0-14): <7 acidic, 7 neutral, >7 alkaline. Universal indicator shows full range. Litmus, methyl orange, and phenolphthalein have specific colour changes.",
        "keywords": [
            r"\bpH\b", r"\b(?:universal|litmus|methyl|phenolphthalein)\s*(?:indicator|paper)",
            r"\bacidic\b", r"\bneutral\b", r"\balkaline\b",
            r"\b(?:red|blue|yellow|orange|pink|purple|green|colourless)\b.*\b(?:acid|base|alkali)",
            r"\bpH\s*(?:scale|value|range|meter|paper|chart)\b",
            r"\bcolour\s*change", r"\bcolour\s*chart\b"
        ],
    },
    "Making Salts": {
        "section": "8. Acids, Bases and Salts",
        "tags": ["acids-bases"],
        "summary": "Salts are produced by neutralising acids with metals, bases, or carbonates. Soluble salts prepared by titration or acid+excess solid; insoluble salts by precipitation.",
        "keywords": [
            r"\bmaking\s*salt", r"\bprepar(?:e|ing|ation)\b.*\bsalt\b",
            r"\bacid\s*\+\s*(?:metal|base|oxide|carbonate|alkali)\b",
            r"\bsoluble\s*salt\b", r"\binsoluble\s*salt\b",
            r"\b(?:sodium|potassium|ammonium|calcium|copper|zinc|iron|lead|barium|silver|magnesium)\s*(?:chloride|nitrate|sulfate|sulphate|carbonate)\b",
            r"\bprecipitat(?:e|ion)\b.*\b(?:salt|reaction|method)\b",
            r"\b(?:filter|evaporat|crystal)\b.*\bsalt\b"
        ],
    },
    "Neutralization": {
        "section": "8. Acids, Bases and Salts",
        "tags": ["acids-bases"],
        "summary": "Neutralisation: H⁺(aq) + OH⁻(aq) → H₂O(l). Applications include treating indigestion, acidic soil, and industrial waste. Titration determines unknown concentrations.",
        "keywords": [
            r"\bneutrali[sz]", r"\btitrat(?:e|ion)\b",
            r"\b(?:indigestion|antacid|stomach)\b",
            r"\b(?:soil|agricultural|lime).*\b(?:acid|pH)",
            r"\bionic\s*equation\b.*\bneutral",
            r"\bH\s*\+\s*.*\bOH\s*[-−]\s*.*\bH2O\b",
            r"\bend[\s-]*point\b", r"\b(?:burette|pipette)\b"
        ],
    },
    "Qualitative Analysis": {
        "section": "8. Acids, Bases and Salts",
        "tags": ["acids-bases"],
        "summary": "Systematic identification of ions: flame tests for cations (Li⁺ red, Na⁺ yellow, K⁺ lilac, Ca²⁺ orange-red, Cu²⁺ blue-green); NaOH/NH₃ tests for cation precipitates; anion tests.",
        "keywords": [
            r"\bflame\s*test\b", r"\b(?:lilac|yellow|red|orange|blue[\s-]*green|brick\s*red|apple\s*green)\s*(?:flame|colour)",
            r"\b(?:white|blue|green|brown|cream|red[\s-]*brown)\s*precipitate",
            r"\badd.*(?:sodium\s*hydroxide|NaOH|ammonia)\b.*\bprecipitate",
            r"\bsilver\s*nitrate\b.*\b(?:white|cream|yellow)\b",
            r"\bbarium\s*(?:chloride|nitrate)\b.*\bwhite\b",
            r"\bhalide\s*test", r"\bsulfate\s*test", r"\bnitrate\s*test",
            r"\bsodium\s*hydroxide.*aluminium\s*(?:foil|powder)"
        ],
    },
    "Solubility Rules": {
        "section": "8. Acids, Bases and Salts",
        "tags": ["acids-bases"],
        "summary": "All sodium, potassium, and ammonium salts are soluble. All nitrates are soluble. Most chlorides are soluble (except AgCl, PbCl₂). Most sulfates are soluble (except BaSO₄, PbSO₄, CaSO₄). Most carbonates and hydroxides are insoluble.",
        "keywords": [
            r"\bsoluble\b", r"\binsoluble\b",
            r"\b(?:sodium|potassium|ammonium)\s*(?:salt|compound)\b.*\bsoluble",
            r"\b(?:nitrate|chloride|sulfate|sulphate|carbonate|hydroxide)\b.*\b(?:soluble|insoluble)",
            r"\bprecipitat(?:e|ion)\s*reaction",
            r"\b(?:barium|lead|calcium|silver)\s*(?:sulfate|sulphate|chloride)\b"
        ],
    },

    # Topic 9: The Periodic Table
    "Periodic Table Trends": {
        "section": "9. The Periodic Table",
        "tags": ["periodic-table"],
        "summary": "Elements are arranged by increasing atomic number. Periods are horizontal rows; groups are vertical columns. Metallic character decreases across a period and increases down a group.",
        "keywords": [
            r"\bperiodic\s*table", r"\bperiod\b.*\bgroup\b",
            r"\b(?:across|down)\s*(?:a\s*)?(?:period|group)\b",
            r"\b(?:metallic|non[\s-]*metallic)\s*character",
            r"\bvalence\s*(?:electron|shell)\b", r"\bouter\s*shell\b",
            r"\b(?:melting|boiling)\s*point\b.*\b(?:period|group|trend)\b",
            r"\bclassif(?:y|ication)\b.*\belement",
            r"\bperiodic\s*trend"
        ],
    },
    "Group 1 Alkali Metals": {
        "section": "9. The Periodic Table",
        "tags": ["periodic-table"],
        "summary": "Group 1 metals (Li, Na, K, Rb, Cs) are soft, reactive metals with low density. Reactivity increases down the group. They react vigorously with water forming alkaline hydroxides and hydrogen.",
        "keywords": [
            r"\b(?:group\s*1|group\s*I|alkali\s*metal)",
            r"\b(?:lithium|sodium|potassium|rubidium|caesium|cesium)\b",
            r"\b(?:Li|Na|K|Rb|Cs)\b", r"\breact.*\bwater\b",
            r"\b(?:fizz|bubble|float|melt|move)\b.*\bwater",
            r"\balkaline\s*(?:solution|hydroxide)\b",
            r"\bsoft\s*metal", r"\blow\s*density", r"\blow\s*melting"
        ],
    },
    "Group 7 Halogens": {
        "section": "9. The Periodic Table",
        "tags": ["periodic-table"],
        "summary": "Group 7 elements (F₂, Cl₂, Br₂, I₂) are diatomic non-metals. Reactivity decreases down the group. A more reactive halogen displaces a less reactive one from its halide salt.",
        "keywords": [
            r"\b(?:group\s*7|group\s*VII|halogen)",
            r"\b(?:fluorine|chlorine|bromine|iodine)\b",
            r"\b(?:F2|Cl2|Br2|I2)\b", r"\bdiatomic\b",
            r"\bdisplacement\s*reaction\b.*\bhalogen",
            r"\b(?:pale|yellow[\s-]*green|green[\s-]*yellow|red[\s-]*brown|brown|grey|purple|dark)\s*(?:gas|liquid|solid|vapour|colour)",
            r"\bchlorine\s*water\b", r"\bbromine\s*water\b"
        ],
    },
    "Group 0 Noble Gases": {
        "section": "9. The Periodic Table",
        "tags": ["periodic-table"],
        "summary": "Noble gases (He, Ne, Ar, Kr, Xe) are monatomic, colourless, and unreactive due to full outer electron shells. Uses: He in balloons, Ar in welding, Ne in signs.",
        "keywords": [
            r"\b(?:noble\s*gas|group\s*0|group\s*VIII)",
            r"\b(?:helium|neon|argon|krypton|xenon)\b",
            r"\b(?:He|Ne|Ar|Kr|Xe)\b", r"\bunreactive\b",
            r"\b(?:full|complete).*(?:outer|valence|shell)",
            r"\b(?:balloon|welding|light|sign|laser)\b",
            r"\bmonatomic\b", r"\b(?:density|boiling).*\b(?:increase|decrease).*\bgroup"
        ],
    },
    "Transition Metals": {
        "section": "9. The Periodic Table",
        "tags": ["periodic-table"],
        "summary": "Transition metals are hard, dense, high-melting, form coloured compounds, have variable oxidation states, and act as catalysts. Examples: Fe, Cu, Mn, Cr, Ni.",
        "keywords": [
            r"\btransition\s*(?:metal|element)",
            r"\bcolou?red\s*compound", r"\bcatalyst\b",
            r"\b(?:variable|multiple)\s*oxidation\s*(?:state|number)",
            r"\b(?:iron|copper|manganese|chromium|nickel)\b",
            r"\b(?:Fe|Cu|Mn|Cr|Ni)\b",
            r"\bhigh\s*(?:density|melting)\b", r"\bhard\b.*\bmetal"
        ],
    },

    # Topic 10: Metals
    "Reactivity of Metals": {
        "section": "10. Metals",
        "tags": ["metals"],
        "summary": "The reactivity series orders metals by tendency to form positive ions: K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Ag > Au. More reactive metals displace less reactive ones.",
        "keywords": [
            r"\breactivity\s*series", r"\bdisplacement\s*reaction",
            r"\b(?:potassium|sodium|calcium|magnesium|aluminium|zinc|iron|lead|copper|silver|gold)\b.*\b(?:react|displace)\b",
            r"\breact.*\b(?:water|steam|acid)\b.*\bmetal",
            r"\bmore\s*reactive.*\bthan\b",
            r"\b(?:K|Na|Ca|Mg|Al|Zn|Fe|Pb|Cu|Ag|Au)\b"
        ],
    },
    "Metal Extraction": {
        "section": "10. Metals",
        "tags": ["metals"],
        "summary": "Metals are extracted from ores. Methods depend on reactivity: electrolysis for K–Al; reduction with carbon for Zn–Fe; occur native for Cu–Au. Iron from blast furnace; aluminium from Hall-Héroult.",
        "keywords": [
            r"\bextract(?:ion|ing)?\b.*\b(?:metal|iron|aluminium|copper|zinc)\b",
            r"\b(?:blast\s*furnace|haematite|bauxite)\b",
            r"\b(?:coke|limestone|slag)\b.*\bfurnace",
            r"\b(?:Hall|Héroult|cryolite)\b",
            r"\b(?:electrolysis|reduction)\b.*\bextract",
            r"\bore\b", r"\b(?:native|uncombined)\b.*\bmetal"
        ],
    },
    "Uses of Metals": {
        "section": "10. Metals",
        "tags": ["metals"],
        "summary": "Metal uses are determined by properties: Al (low density, corrosion-resistant) for aircraft; Cu (conductivity, malleability) for wiring; Fe/steel for construction. Alloys have improved properties.",
        "keywords": [
            r"\buses?\s*of\b.*\b(?:metal|aluminium|copper|iron|steel|zinc)\b",
            r"\balloy\b.*\b(?:strong|hard|corrosion)", r"\bstainless\s*steel\b",
            r"\b(?:aircraft|wire|wiring|construction|building|cooking|can|foil)\b",
            r"\b(?:lightweight|light|dense|strong|malleable|ductile|corrosion)\b.*\buse"
        ],
    },
    "Rusting of Iron": {
        "section": "10. Metals",
        "tags": ["metals"],
        "summary": "Rusting requires oxygen AND water. Prevention methods: barrier protection (paint, oil, plastic, tin-plating), sacrificial protection (galvanising with zinc), and alloying (stainless steel).",
        "keywords": [
            r"\brust", r"\bcorrosion\b",
            r"\bsacrificial\s*protect", r"\bgalvani[sz]",
            r"\b(?:paint|oil|grease|plastic|coating|tin|chrome)\b.*\b(?:prevent|protect|stop)\b",
            r"\b(?:oxygen|air|water|moisture).*\b(?:rust|corrosion)\b",
            r"\b(?:zinc|magnesium)\b.*\b(?:protect|sacrificial)\b",
            r"\bstainless\s*steel\b"
        ],
    },

    # Topic 11: Air and Water
    "Composition of Air": {
        "section": "11. Air and Water",
        "tags": ["environmental-chem"],
        "summary": "Clean air contains ~78% N₂, ~21% O₂, ~0.9% Ar, ~0.04% CO₂. Oxygen percentage can be determined by reaction with copper or phosphorus in a closed system.",
        "keywords": [
            r"\b(?:air|atmosphere)\b.*\b(?:nitrogen|oxygen|argon|carbon\s*dioxide)\b",
            r"\b(?:78|79)\s*%", r"\b(?:21|20)\s*%", r"\b0[\.,]04\s*%",
            r"\b(?:composition|component|gas)\b.*\b(?:air|atmosphere)",
            r"\bpercentage\s*of\s*oxygen\b", r"\bcopper\b.*\b(?:syringe|air)\b",
            r"\b(?:phosphorus|iron)\b.*\b(?:air|oxygen)\b"
        ],
    },
    "Air Pollution": {
        "section": "11. Air and Water",
        "tags": ["environmental-chem"],
        "summary": "Pollutants from fossil fuel combustion: CO (toxic, binds hemoglobin), SO₂ (acid rain), NOx (acid rain, photochemical smog), particulates (respiratory issues). Catalytic converters reduce emissions.",
        "keywords": [
            r"\b(?:air\s*)?pollution", r"\b(?:pollutant|emission)\b",
            r"\bcarbon\s*monoxide\b", r"\bsulfur\s*dioxide\b", r"\bSO2\b",
            r"\bnitrogen\s*oxide", r"\bNOx?\b", r"\bNO2?\b",
            r"\bacid\s*rain\b", r"\bcatalytic\s*converter",
            r"\b(?:photochemical\s*)?smog\b", r"\bflue\s*gas\b",
            r"\bdesulfurisation", r"\bparticulate",
            r"\b(?:poisonous|toxic|harmful|respiratory)\b"
        ],
    },
    "Climate Change and Greenhouse Gases": {
        "section": "11. Air and Water",
        "tags": ["environmental-chem"],
        "summary": "Greenhouse gases (CO₂, CH₄, water vapour) trap infrared radiation, causing global warming. Carbon footprint measures total greenhouse gas emissions from an activity or product.",
        "keywords": [
            r"\bgreenhouse\b", r"\bglobal\s*warming\b",
            r"\bclimate\s*change\b", r"\bcarbon\s*dioxide\b",
            r"\bmethane\b", r"\bcarbon\s*footprint",
            r"\binfrared\s*radiation\b", r"\b(?:trap|absorb|reflect).*\b(?:heat|radiation|IR)\b"
        ],
    },
    "Water Treatment": {
        "section": "11. Air and Water",
        "tags": ["environmental-chem"],
        "summary": "Potable water production: sedimentation, filtration, chlorination (or ozone/UV). Desalination by distillation or reverse osmosis. Water is tested for purity by checking boiling point.",
        "keywords": [
            r"\bwater\s*treatment", r"\bpotable\b",
            r"\b(?:sedimentation|filtration|chlorination|chlorine)\b",
            r"\bdesalinat", r"\breverse\s*osmosis",
            r"\b(?:drinking|clean|pure)\s*water", r"\bwater\s*purif",
            r"\bboiling\s*point\b.*\b(?:100|pure|water|test)\b",
            r"\b(?:sewage|waste\s*water)\b"
        ],
    },

    # Topic 12: Sulfur
    "Sulfur and Compounds": {
        "section": "12. Sulfur",
        "tags": ["environmental-chem"],
        "summary": "Sulfur sources: natural (volcanoes) and fossil fuels. SO₂ produced by burning sulfur or roasting sulfide ores. Contact process: SO₂ + O₂ ⇌ SO₃ using V₂O₅ catalyst, then SO₃ + H₂SO₄ → oleum → H₂SO₄.",
        "keywords": [
            r"\bsulfur\b", r"\bsulphur\b", r"\bSO2\b", r"\bSO3\b",
            r"\bsulfuric\s*acid\b", r"\bH2SO4\b",
            r"\bContact\s*process\b", r"\bvanadium\b", r"\bV2O5\b",
            r"\boleum\b", r"\bsulfate\b", r"\bsulphate\b",
            r"\b(?:volcano|volcanic|fossil\s*fuel)\b.*\bsulfur"
        ],
    },
    "Uses of Sulfur Compounds": {
        "section": "12. Sulfur",
        "tags": ["environmental-chem"],
        "summary": "Sulfuric acid is the most manufactured chemical: used in fertilisers, detergents, paints, plastics, metal processing, and as an electrolyte in car batteries.",
        "keywords": [
            r"\b(?:use|application)\b.*\b(?:sulfur|sulphur|sulfuric|sulphuric)\b",
            r"\b(?:fertiliser|fertilizer|detergent|paint|plastic|battery|metal)\b.*\b(?:sulfuric|acid)\b",
            r"\bNPK\b", r"\b(?:ammonium|phosphate)\b.*\bfertilis"
        ],
    },

    # Topic 13: Carbonates
    "Carbonates": {
        "section": "13. Carbonates",
        "tags": ["reactions"],
        "summary": "Metal carbonates thermally decompose to metal oxide + CO₂ (except Group 1 carbonates which are stable). The limestone cycle: CaCO₃ → CaO + CO₂, CaO + H₂O → Ca(OH)₂, Ca(OH)₂ + CO₂ → CaCO₃.",
        "keywords": [
            r"\bcarbonate\b", r"\blimestone\b",
            r"\bCaCO3\b", r"\bcalcium\s*carbonate\b",
            r"\bthermal\s*decomposition", r"\b(?:lime|quicklime|slaked\s*lime)\b",
            r"\bcalcium\s*oxide\b", r"\bCaO\b",
            r"\bcalcium\s*hydroxide\b", r"\bCa\(OH\)2\b",
            r"\b(?:cement|mortar|concrete)\b"
        ],
    },

    # Topic 14: Organic Chemistry
    "Organic Chemistry Fundamentals": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Organic chemistry is the study of carbon compounds. Key concepts: homologous series, functional groups, isomerism, and systematic nomenclature. Compounds are classified by functional group.",
        "keywords": [
            r"\bhomologous\s*series", r"\bfunctional\s*group",
            r"\b(?:general|molecular|structural|displayed)\s*formula",
            r"\b(?:empirical|molecular|structural|displayed)\s*formula",
            r"\bisomer", r"\bnomenclature\b",
            r"\borganic\s*compound", r"\b(?:saturated|unsaturated)\b"
        ],
    },
    "Alkanes": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Alkanes are saturated hydrocarbons (CₙH₂ₙ₊₂). First four: methane (CH₄), ethane (C₂H₆), propane (C₃H₈), butane (C₄H₁₀). They undergo combustion and substitution reactions with halogens (UV light).",
        "keywords": [
            r"\balkan", r"\b(?:methane|ethane|propane|butane)\b",
            r"\bCH4\b", r"\bC2H6\b", r"\bC3H8\b", r"\bC4H10\b",
            r"\bsaturated\s*hydrocarbon", r"\bCnH2n\+2\b",
            r"\bsubstitution\b.*\b(?:halogen|chlorine|bromine|UV|sunlight)",
            r"\b(?:complete|incomplete)\s*combustion\b"
        ],
    },
    "Alkenes": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Alkenes are unsaturated hydrocarbons with C=C double bond (CₙH₂ₙ). Ethene (C₂H₄) is the simplest. They undergo addition reactions (bromine, hydrogen, steam) and polymerisation.",
        "keywords": [
            r"\balken", r"\bethene\b", r"\bC2H4\b",
            r"\bunsaturated\s*hydrocarbon", r"\bC\s*=\s*C\b",
            r"\baddition\s*(?:reaction|polymeri[sz])",
            r"\bbromine\s*water\b.*\b(?:decolouri|test)\b",
            r"\b(?:orange|brown|red).*\b(?:colourless|decolouri)\b",
            r"\bCnH2n\b"
        ],
    },
    "Alcohols": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Alcohols contain the –OH functional group (CₙH₂ₙ₊₁OH). Ethanol (C₂H₅OH) is made by fermentation (glucose → ethanol + CO₂, yeast, anaerobic, ~35°C) or hydration of ethene (C₂H₄ + H₂O, 300°C, 60 atm, H₃PO₄ catalyst).",
        "keywords": [
            r"\balcohol\b", r"\bethanol\b", r"\bmethanol\b",
            r"\bC2H5OH\b", r"\bfermentation\b",
            r"\b(?:yeast|zymase|anaerobic|glucose)\b.*\b(?:ethanol|alcohol)",
            r"\bhydration\b.*\bethene",
            r"\bhydroxyl\b", r"\b[-−]OH\b", r"\bOH\s*group\b"
        ],
    },
    "Carboxylic Acids": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Carboxylic acids contain the –COOH functional group. Ethanoic acid (CH₃COOH) is a weak acid found in vinegar. They react with alcohols to form esters (esterification).",
        "keywords": [
            r"\bcarboxylic\s*acid", r"\bethanoic\s*acid\b",
            r"\bCH3COOH\b", r"\bCOOH\b", r"\bcarboxyl\b",
            r"\b(?:vinegar|weak\s*acid)\b.*\bethanoic",
            r"\bester", r"\besterif",
            r"\b(?:acid|catalyst|sulfuric)\b.*\b(?:alcohol|ester)"
        ],
    },
    "Esters": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Esters (RCOOR') are formed by reacting carboxylic acids with alcohols (esterification, H₂SO₄ catalyst). They have fruity smells and are used as flavourings, fragrances, and solvents.",
        "keywords": [
            r"\bester", r"\besterif",
            r"\b(?:fruity|sweet|pleasant)\s*smell",
            r"\b(?:flavour|fragrance|perfume|solvent)\b.*\bester",
            r"\b(?:alcohol|acid)\b.*\b(?:ester|condensation)\b",
            r"\bethyl\s*ethanoate\b"
        ],
    },
    "Polymers": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Addition polymers: monomers with C=C join without byproducts (poly(ethene), poly(propene), PVC). Condensation polymers: monomers join with elimination of small molecule (nylon, PET, proteins).",
        "keywords": [
            r"\bpolymer", r"\bpolymeri[sz]",
            r"\b(?:poly\(?ethene\)?|poly\(?propene\)?|PVC|polythene|polypropylene)\b",
            r"\bmonomer\b", r"\baddition\s*polymer",
            r"\bcondensation\s*polymer", r"\b(?:nylon|PET|polyester)\b",
            r"\b(?:plastic|plastics)\b.*\b(?:disposal|recycl|biodegrad|non[\s-]*biodegrad)",
            r"\brepeating\s*unit"
        ],
    },
    "Fuels and Petroleum": {
        "section": "14. Organic Chemistry",
        "tags": ["organic-chem"],
        "summary": "Petroleum is separated by fractional distillation into fractions (refinery gas, petrol, naphtha, kerosene, diesel, fuel oil, bitumen). Cracking breaks long alkanes into shorter alkanes + alkenes.",
        "keywords": [
            r"\b(?:petroleum|crude\s*oil|fossil\s*fuel)\b",
            r"\bfractional\s*distillation", r"\bfraction\b",
            r"\b(?:refinery\s*gas|petrol|gasoline|naphtha|kerosene|paraffin|diesel|fuel\s*oil|lubricat|bitumen)\b",
            r"\bcrack", r"\b(?:thermal|catalytic)\s*crack",
            r"\b(?:boiling\s*point|viscosity|flammability|volatility)\b.*\bfraction",
            r"\b(?:renewable|biofuel|biodiesel|bioethanol)\b"
        ],
    },

    # Cross-cutting
    "Chemical Equations and Calculations": {
        "section": "Cross-cutting Skills",
        "tags": ["stoichiometry"],
        "summary": "Balancing chemical equations using state symbols (s, l, g, aq). Writing ionic equations by removing spectator ions. Converting between mass, moles, concentration, and gas volume.",
        "keywords": [
            r"\bbalanc(?:e|ing)\b.*\b(?:equation|chemical)\b",
            r"\bstate\s*symbol", r"\bionic\s*equation",
            r"\bspectator\s*ion", r"\b(?:s|l|g|aq)\b",
            r"\b(?:half[\s-]*equation|half[\s-]*reaction)\b",
            r"\bcalculat.*\b(?:mole|mass|volume|concentrat)\b"
        ],
    },
}

# ── Classification ────────────────────────────────────────────────

def classify_entry(entry):
    """Classify a single Q+A entry to one or more topics based on keyword matching."""
    answer = entry.get('answer', '')
    question = entry.get('questionText', '')
    text = (answer + ' ' + question).lower()

    scores = {}
    for topic_name, topic_info in TOPICS.items():
        score = 0
        for pattern in topic_info['keywords']:
            if re.search(pattern, text, re.IGNORECASE):
                score += 1
        if score > 0:
            scores[topic_name] = score

    if not scores:
        return ['Mixed Chemistry']

    # Require at least 3 keyword matches to classify (stricter to avoid cross-contamination)
    qualified = [t for t, s in scores.items() if s >= 3]
    if qualified:
        return qualified
    elif scores:
        best = max(scores, key=scores.get)
        if scores[best] >= 2:
            return [best]
    return ['Mixed Chemistry']


def extract_key_facts(entries):
    """Extract cleaned, study-ready facts from mark scheme answers."""
    facts = []
    seen = set()

    for entry in entries:
        answer = entry.get('answer', '').strip()
        if not answer or len(answer) < 3:
            continue

        # Clean mark scheme formatting
        cleaned = answer
        cleaned = re.sub(r'\s*\(\d+\)', '', cleaned)  # Remove (1) (2) marks
        cleaned = re.sub(r'^\d+\s*', '', cleaned)  # Remove leading numbers
        cleaned = re.sub(r'one mark each for any \d+ of:?\s*', '', cleaned)
        cleaned = re.sub(r'(?:IF|if) \d+ marks? not scored.*', '', cleaned)
        cleaned = re.sub(r'max\s*\d+\s*marks?', '', cleaned)
        cleaned = re.sub(r'\baward\s+\d+\s+mark', '', cleaned)
        cleaned = cleaned.strip(' ;,•')

        # Split multi-point answers
        points = re.split(r'\s*[;•]\s*|\s*\d+\s*[.)]\s*', cleaned)
        for point in points:
            point = point.strip()
            if len(point) < 10 or len(point) > 200:
                continue
            # Deduplicate (case-insensitive)
            key = point.lower()
            if key not in seen:
                seen.add(key)
                facts.append(point)

    return facts[:30]  # Limit per topic


def extract_equations(entries):
    """Find chemical equations and reactions from mark scheme answers."""
    equations = set()
    for entry in entries:
        answer = entry.get('answer', '')
        # Find chemical formulas
        formulas = re.findall(r'[A-Z][a-z]?\d*(?:\([A-Z][a-z]?\d*\))?\d*[→+]+[A-Z][a-z]?\d*', answer)
        for f in formulas:
            if len(f) > 8:
                equations.add(f)
    return sorted(equations)[:10]


def extract_paper_keywords(entries):
    """Extract the most distinctive keywords that appear in mark scheme answers for this topic."""
    from collections import Counter

    # Common chemistry stop words to filter
    stop = {'the', 'a', 'an', 'of', 'in', 'to', 'and', 'is', 'for', 'on', 'with',
            'or', 'as', 'at', 'by', 'from', 'be', 'are', 'was', 'has', 'have',
            'not', 'if', 'but', 'can', 'all', 'will', 'one', 'two', 'mark',
            'marks', 'each', 'any', 'than', 'more', 'less', 'most', 'some',
            'this', 'that', 'which', 'when', 'where', 'who', 'may', 'also',
            'other', 'their', 'its', 'been', 'were', 'had', 'they', 'them',
            'about', 'would', 'could', 'should', 'answer', 'question',
            'accept', 'reject', 'ignore', 'allow', 'award', 'credit', 'max',
            'correct', 'incorrect', 'wrong', 'right', 'must', 'need', 'required',
            'used', 'using', 'use', 'give', 'given', 'named', 'name', 'state',
            'describe', 'explain', 'identify', 'suggest', 'calculate', 'determine',
            'complete', 'draw', 'label', 'tick', 'box', 'shown', 'show', 'diagram',
            'figure', 'table', 'graph', 'paper', 'mark', 'scheme', 'question',
            'write', 'written', 'word', 'words', 'number', 'numbers',
            'example', 'examples', 'different', 'same', 'following', 'follows',
            'above', 'below', 'total', 'pmt', 'ucl', 'ucles', 'cambridge',
            'igcse', 'chemistry', 'paper', 'theory', 'core', '0620', '0971',
            'answer', 'brackets', '2', '3'}

    words = Counter()
    for entry in entries:
        answer = entry.get('answer', '').lower()
        # Extract individual meaningful words
        tokens = re.findall(r'\b[a-z][a-z]{2,}\b', answer)
        for t in tokens:
            if t not in stop:
                words[t] += 1

    # Return top 15 keywords
    return [word for word, count in words.most_common(15)]


def extract_question_types(entries):
    """Identify recurring question patterns from mark schemes."""
    patterns = Counter()
    for entry in entries:
        answer = entry.get('answer', '').lower()
        entry_type = entry.get('type', 'short')
        marks = entry.get('marks', 1)

        if any(w in answer for w in ['describe', 'explain', 'suggest', 'discuss']):
            patterns['Extended writing (describe/explain/suggest)'] += 1
        elif any(w in answer for w in ['calculate', 'work out', 'determine']):
            patterns['Calculation question'] += 1
        elif any(w in answer for w in ['draw', 'label', 'sketch', 'complete the']):
            patterns['Diagram/labelling task'] += 1
        elif any(w in answer for w in ['tick', 'box', 'circle']):
            patterns['Multiple choice / tick-box'] += 1
        elif any(w in answer for w in ['state', 'give', 'name', 'identify', 'write']):
            patterns['Short recall (state/give/name)'] += 1
        elif entry_type == 'long' or marks >= 3:
            patterns['Extended writing (describe/explain/suggest)'] += 1
        else:
            patterns['Short recall (state/give/name)'] += 1

    return [p for p, c in patterns.most_common(5) if c >= 1]


def extract_paper_sources(entries):
    """List the most relevant past paper sources for a topic."""
    papers = defaultdict(list)
    for entry in entries:
        paper = entry.get('paper', '')
        code = entry.get('code', '')
        session = entry.get('session', '')
        q_num = entry.get('qNum', '')
        label = entry.get('label', '')
        marks = entry.get('marks', 0)

        key = f"{code} {session}"
        papers[key].append(f"Q{q_num}{label} ({marks}m)")

    sources = []
    for paper_key, questions in sorted(papers.items()):
        q_summary = ', '.join(questions[:3])
        if len(questions) > 3:
            q_summary += f' (+{len(questions)-3} more)'
        sources.append(f"- {paper_key}: {q_summary}")

    return sources[:12]


# ── Markdown Generation ───────────────────────────────────────────

def generate_markdown_file(topic_name, topic_info, entries):
    """Generate a single .md wiki file."""
    facts = extract_key_facts(entries)
    equations = extract_equations(entries)
    question_types = extract_question_types(entries)
    sources = extract_paper_sources(entries)
    keywords = extract_paper_keywords(entries)

    # ── Build wikilinks to related topics ──
    # Topics in the same section are related
    same_section = [
        name for name, info in TOPICS.items()
        if info['section'] == topic_info['section'] and name != topic_name
    ]
    # Also link to broader topics and key cross-references
    cross_refs = {
        "Atomic Structure": ["Periodic Table Trends", "Ions and Ionic Bonds", "Covalent Bonding"],
        "Ions and Ionic Bonds": ["Atomic Structure", "Giant Structures", "Electrolysis"],
        "Covalent Bonding": ["Atomic Structure", "Giant Structures", "Organic Chemistry Fundamentals"],
        "Electrolysis": ["Ions and Ionic Bonds", "Redox Reactions", "Metal Extraction"],
        "Reactivity of Metals": ["Metal Extraction", "Rusting of Iron", "Redox Reactions"],
        "Acids and Bases": ["Neutralization", "Making Salts", "Indicators and pH"],
        "Alkanes": ["Alkenes", "Fuels and Petroleum", "Organic Chemistry Fundamentals"],
        "Alkenes": ["Alkanes", "Polymers", "Alcohols"],
        "Polymers": ["Alkenes", "Organic Chemistry Fundamentals", "Fuels and Petroleum"],
    }

    related = same_section[:4]
    extra = cross_refs.get(topic_name, [])
    for e in extra:
        if e not in related:
            related.append(e)
    related = related[:8]

    # ── Build content sections ──
    content_parts = []

    # Core explanation
    content_parts.append(f"**{topic_info['summary']}**\n")

    # Key facts from mark schemes
    if facts:
        content_parts.append("### Key Concepts from Past Papers\n")
        for fact in facts[:8]:
            content_parts.append(f"- {fact}")
        content_parts.append("")

    # Common question types
    if question_types:
        content_parts.append("### Common Question Types\n")
        for qt in question_types:
            content_parts.append(f"- {qt}")
        content_parts.append("")

    # Key equations
    if equations:
        content_parts.append("### Key Equations\n")
        for eq in equations[:5]:
            content_parts.append(f"- `{eq}`")
        content_parts.append("")

    # Study tips
    content_parts.append("### Exam Tips\n")
    paper_count = len(set(e.get('paper', '') for e in entries))
    content_parts.append(f"- This topic appears in **{paper_count} papers** in the database")
    content_parts.append(f"- Total Q+A entries: **{len(entries)}**")
    if entries:
        avg_marks = sum(e.get('marks', 0) for e in entries) / max(len(entries), 1)
        content_parts.append(f"- Average marks per question: **{avg_marks:.1f}**")
    content_parts.append("")

    # Keywords from past papers
    if keywords:
        content_parts.append("### Keywords from Past Papers\n")
        content_parts.append(', '.join(f'`{kw}`' for kw in keywords))
        content_parts.append("")

    # ── Assemble file ──
    tags = ' #igcse #chemistry' + ''.join(f' #{t}' for t in topic_info['tags'])

    md = f"""# {topic_name}

**Summary**: {topic_info['summary']}
**Tags**:{tags}
**Created**: {NOW}
**Last Updated**: {NOW}

---

## Content

{chr(10).join(content_parts)}
## Related Notes

"""
    for r in related:
        md += f"- [[{r}]]\n"

    md += "\n## Past Paper Sources\n\n"
    if sources:
        for s in sources:
            md += f"{s}\n"
    else:
        md += "See [[IGCSE-Chem-Index]] for full paper inventory.\n"

    return md


def generate_index_file(topic_data):
    """Generate IGCSE-Chem-Index.md."""
    # Group topics by section
    sections = defaultdict(list)
    for topic_name, info in TOPICS.items():
        sections[info['section']].append((topic_name, topic_data.get(topic_name, [])))

    body = ""
    for section_name, topics in sections.items():
        body += f"### {section_name}\n\n"
        for topic_name, entries in topics:
            count = len(entries)
            papers = len(set(e.get('paper', '') for e in entries))
            body += f"- [[{topic_name}]] — {count} Q+A pairs across {papers} papers\n"
        body += "\n"

    md = f"""# IGCSE Chemistry Index

**Summary**: Complete index of IGCSE Chemistry (0620/0971) concepts organised by syllabus topic. All content extracted and verified from real past papers and mark schemes.
**Tags**: #index #igcse #chemistry #hub
**Created**: {NOW}
**Last Updated**: {NOW}

---

{body}
## Data Sources

- 38 paired question papers + mark schemes (2015–2024)
- 1,229 Q+A pairs classified into {len(TOPICS)} topics
- MS-driven extraction from `chem-exam-data.js` and `chem-content-db.js`

## Related Indexes

- [[Chem-Index]]
- [[CS-Index]]
"""
    return md


# ── Main ──────────────────────────────────────────────────────────

def main():
    entries, exams = load_data()

    # Also extract Q+A from exam-data.js papers
    print("\nExtracting from exam papers...")
    exam_entries = []
    for paper_id, paper in exams.items():
        if not isinstance(paper, dict):
            continue
        for question in paper.get('questions', []):
            q_num = question.get('num', 0)
            for part in question.get('parts', []):
                exam_entries.append({
                    'paper': paper_id.replace('0921_', ''),
                    'code': paper.get('code', ''),
                    'session': paper.get('session', ''),
                    'qNum': q_num,
                    'label': part.get('label', ''),
                    'type': part.get('type', 'short'),
                    'marks': part.get('marks', 0),
                    'answer': part.get('answer', ''),
                    'questionText': part.get('question', ''),
                })
    print(f"  Extracted {len(exam_entries)} parts from {len(exams)} papers")

    # Combine both sources
    all_entries = entries + exam_entries
    print(f"  Total: {len(all_entries)} entries")

    # Classify all entries
    print("\nClassifying entries...")
    topic_entries = defaultdict(list)
    unclassified = []

    # Map original content-db topics to our topic names
    ORIGINAL_TOPIC_MAP = {
        'Acids, Bases & Salts': ['Acids and Bases', 'Indicators and pH', 'Making Salts',
                                 'Neutralization', 'Qualitative Analysis', 'Solubility Rules'],
        'Air, Water & Environment': ['Air Pollution', 'Climate Change and Greenhouse Gases',
                                      'Composition of Air', 'Water Treatment'],
        'Atomic Structure & Periodic Table': ['Atomic Structure', 'Periodic Table Trends'],
        'Bonding & Structure': ['Ions and Ionic Bonds', 'Covalent Bonding', 'Metallic Bonding',
                                 'Giant Structures'],
        'Chemical Analysis & Tests': ['Chemical Tests', 'Qualitative Analysis'],
        'Electrolysis': ['Electrolysis', 'Electrolysis of Aqueous Solutions', 'Electrolysis Applications'],
        'Energy Changes': ['Energetics of Reactions', 'Bond Energy Calculations'],
        'Metals & Reactivity': ['Reactivity of Metals', 'Metal Extraction', 'Uses of Metals',
                                'Rusting of Iron', 'Transition Metals'],
        'Organic Chemistry': ['Organic Chemistry Fundamentals', 'Alkanes', 'Alkenes',
                              'Alcohols', 'Carboxylic Acids', 'Esters', 'Polymers',
                              'Fuels and Petroleum'],
        'Rates of Reaction': ['Rates of Reaction'],
        'Stoichiometry & Moles': ['Relative Masses and Moles', 'Empirical and Molecular Formulae',
                                   'Reacting Masses', 'Concentration and Gas Volumes',
                                   'Chemical Equations and Calculations'],
        'Sulfur & Compounds': ['Sulfur and Compounds', 'Uses of Sulfur Compounds'],
        'Mixed Chemistry': None,  # Will be classified by keywords
    }

    # First pass: assign entries from original topics
    for entry in entries:
        orig_topic = entry.get('_topic', 'Mixed Chemistry')
        mapped = ORIGINAL_TOPIC_MAP.get(orig_topic)
        if mapped:
            for t in mapped:
                if entry not in topic_entries[t]:
                    topic_entries[t].append(entry)
        else:
            # Try keyword classification for Mixed Chemistry and unmapped
            topics = classify_entry(entry)
            if 'Mixed Chemistry' not in topics:
                for t in topics:
                    if entry not in topic_entries[t]:
                        topic_entries[t].append(entry)
            else:
                unclassified.append(entry)

    # Second pass: classify exam-data entries (which have no original topic)
    for entry in exam_entries:
        topics = classify_entry(entry)
        if 'Mixed Chemistry' not in topics and topics:
            for t in topics:
                if entry not in topic_entries[t]:
                    topic_entries[t].append(entry)
        else:
            unclassified.append(entry)

    # Print stats
    print(f"\nClassification results:")
    for topic_name in sorted(TOPICS.keys()):
        count = len(topic_entries.get(topic_name, []))
        print(f"  {topic_name}: {count} entries")
    print(f"  Unclassified: {len(unclassified)} entries")

    # Generate files
    WIKI_DIR.mkdir(parents=True, exist_ok=True)
    generated = 0

    for topic_name, topic_info in TOPICS.items():
        entries_for_topic = topic_entries.get(topic_name, [])

        if entries_for_topic:
            md_content = generate_markdown_file(topic_name, topic_info, entries_for_topic)
        else:
            # Generate a skeleton file with research content
            md_content = generate_markdown_file(topic_name, topic_info, [])

        filepath = WIKI_DIR / f"{topic_name}.md"
        with open(filepath, 'w') as f:
            f.write(md_content)
        generated += 1

    # Generate index
    index_md = generate_index_file(topic_entries)
    with open(WIKI_DIR / "IGCSE-Chem-Index.md", 'w') as f:
        f.write(index_md)
    generated += 1

    # Write unclassified entries for manual review
    if unclassified:
        audit_path = WIKI_DIR / "_unclassified_entries.md"
        with open(audit_path, 'w') as f:
            f.write(f"# Unclassified Entries ({len(unclassified)})\n\n")
            f.write("These entries could not be classified. Please review and assign to topics.\n\n")
            for entry in unclassified:
                f.write(f"- **{entry.get('paper', '?')}** {entry.get('label', '?')}: {entry.get('answer', '?')[:200]}\n")
        print(f"\n  {len(unclassified)} unclassified entries → _unclassified_entries.md for review")

    print(f"\n✓ Generated {generated} files in {WIKI_DIR}")
    print(f"  {len(topic_entries)} topic files + 1 index")


if __name__ == '__main__':
    main()
